### ISSUE TITLE
How to write CoffeeScript directive

### ISSUE THREAD

**Issue by Shyam-Chen** [jsoverson/preprocess#108]
not working
```coffee
# error
require './modules'
# @if ENV='prod'
require './templates'
# @endif

angular
  .module 'app', [
    'ngComponentRouter'
    'ngMaterial'
    'firebase'
    'app.core'
    'app.shared'
    # @if ENV='prod'
    'app.template'
    # @endif
  ]
```
```bash
# error message
Cannot find module './templates'
```

```coffee
# ok (bad practice)
require './modules'
`/* @if ENV='prod' **`
require './templates'
`/* @endif */`

angular
  .module 'app', [
    'ngComponentRouter'
    'ngMaterial'
    'firebase'
    'app.core'
    'app.shared'
    `/* @if ENV='prod' **`
    'app.template'
    `/* @endif */`
  ]
```

```coffee
# gulpfile.coffee
[...]
preprocessify = require 'preprocessify'
[...]
    firstBundle = ->
      bundler
        .transform preprocessify (ENV: 'dev'), includeExtensions: '.coffee'
        .bundle()
        .on 'error', handleCompileErrors
        .pipe bundleShared()
[...]
```

**Comment by Shyam-Chen** [comment]
```coffee
require './modules'

di = [
  'ngComponentRouter'
  'ngMaterial'
  'firebase'
  'app.core'
  'app.shared'
]

### @if ENV='prod' ###
require './templates'
di.push 'app.template'
### @endif ###

angular.module 'app', di
```

**Comment by Shyam-Chen** [comment]
build failing in CI

**Comment by Shyam-Chen** [comment]
```coffee
# karma.conf.coffee
preprocessify = require 'preprocessify'
[...]
    transform: ['coffeeify', [
      preprocessify (ENV: 'dev'), includeExtensions: '.coffee'
    ]]
[...]
```
